AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Layout/BeginEndAlignment:
    Enabled: true
  Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "fusuma-plugin-*.gemspec"

Layout/LineLength:
  Max: 100
  Exclude:
    - "**/*_spec.rb"
    - "fusuma-plugin-*.gemspec"

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
